name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Install server dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./packages/product
      - name: Analysing Products services
        run: |
          PYTHONPATH="." pylint $(git ls-files '*.py')
        working-directory: ./packages/product/src
