name: "Image Push"
description: "Push the provided service's docker image"
inputs:
  service-name:
    description: "Name of the service to deploy"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build docker image
      run: |
        docker build -t ecommerce-${{ inputs.service-name }} .
      shell: bash
      working-directory: ./packages/${{ inputs.service-name }}

    - name: Tag docker image
      run: |
        docker tag ecommerce-${{ inputs.service-name }}:latest 776733965771.dkr.ecr.us-east-1.amazonaws.com/ecommerce-${{ inputs.service-name }}:latest
      shell: bash
      working-directory: ./packages/${{ inputs.service-name }}

    - name: Push image to repository
      run: |
        docker push 776733965771.dkr.ecr.us-east-1.amazonaws.com/ecommerce-${{ inputs.service-name }}:latest
      shell: bash
      working-directory: ./packages/${{ inputs.service-name }}
